# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-29 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180129_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='signedagreementform',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.DataProject'),
            preserve_default=False,
        ),
    ]
