# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-30 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_signedagreementform_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
