# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-02 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180130_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_email', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[set(['Waiting', 'WAITING'])], default='WAITING', max_length=20, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Participant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Team')),
            ],
        ),
    ]
