# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-02 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20180202_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='data_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.DataProject'),
        ),
    ]
