# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-05 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20180202_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='data_challenge',
        ),
        migrations.AddField(
            model_name='participant',
            name='data_challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.DataProject'),
            preserve_default=False,
        ),
    ]
