# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-06 19:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20180205_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('logo', models.FileField(blank=True, null=True, upload_to=projects.models.get_institution_logo_upload_path)),
            ],
        ),
        migrations.AlterField(
            model_name='dataproject',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.Institution'),
        ),
        migrations.AlterField(
            model_name='signedagreementform',
            name='agreement_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.AgreementForm'),
        ),
        migrations.AlterField(
            model_name='signedagreementform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
