# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-06 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20180206_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.models.get_institution_logo_upload_path),
        ),
    ]
