# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 21:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20180206_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='project_visibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agreementform',
            name='form_html',
            field=models.FileField(upload_to=projects.models.models.get_agreement_form_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html'])]),
        ),
    ]
