# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20180208_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataproject',
            old_name='project_visibility',
            new_name='project_visible',
        ),
    ]
