# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20180208_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_location_type', models.CharField(choices=[('FILE_SERVICE_URL', 'FileService Signed URL'), ('EXTERNAL_APP_URL', 'External Application URL')], max_length=15)),
                ('data_location', models.CharField(max_length=250)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.DataProject')),
            ],
        ),
    ]
