# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_merge_20180212_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementform',
            name='short_name',
            field=models.CharField(default='X', max_length=6, verbose_name='short_name'),
            preserve_default=False,
        ),
    ]
