# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_agreementform_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ready', 'Ready to be activated'), ('Active', 'Activated'), ('Deactivated', 'Deactivated')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='agreementform',
            name='short_name',
            field=models.CharField(max_length=6),
        ),
    ]
