# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20180213_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datagate',
            name='data_location_type',
            field=models.CharField(choices=[('FILE_SERVICE_URL', 'FileService Signed URL'), ('EXTERNAL_APP_URL', 'External Application URL')], max_length=50),
        ),
    ]
