# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0020_auto_20180219_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('file_location_type', models.CharField(choices=[('FILE_SERVICE_URL', 'FileService Signed URL'), ('EXTERNAL_APP_URL', 'External Application URL'), ('S3_BUCKET', 'S3 Bucket directly accessed by Hyatio')], max_length=100)),
                ('file_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HostedFileDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_date', models.DateTimeField(auto_now_add=True)),
                ('hosted_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.HostedFile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='datagate',
            name='data_location_type',
            field=models.CharField(choices=[('FILE_SERVICE_URL', 'FileService Signed URL'), ('EXTERNAL_APP_URL', 'External Application URL'), ('S3_BUCKET', 'S3 Bucket directly accessed by Hyatio')], max_length=50),
        ),
    ]
