# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 18:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20180226_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedfiledownload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
