# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20180227_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedfiledownload',
            name='hosted_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.HostedFile'),
        ),
    ]
