# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20180227_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedfile',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.DataProject'),
            preserve_default=False,
        ),
    ]
