# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_hostedfile_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedfile',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='hostedfile',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
