# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20180227_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='registration_open',
            field=models.BooleanField(default=False),
        ),
    ]
