# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_participantsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='accepting_user_submissions',
            field=models.BooleanField(default=False),
        ),
    ]
