# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_dataproject_accepting_user_submissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantsubmission',
            name='file',
        ),
        migrations.RemoveField(
            model_name='participantsubmission',
            name='id',
        ),
        migrations.AddField(
            model_name='participantsubmission',
            name='location',
            field=models.CharField(default=None, max_length=12, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantsubmission',
            name='uuid',
            field=models.UUIDField(default=None, primary_key=True, serialize=False, unique=True),
        ),
    ]
