# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 17:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_participantsubmissiondownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='submission_form_html',
            field=models.FileField(default=None, upload_to=projects.models.get_submission_form_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html'])]),
            preserve_default=False,
        ),
    ]
