# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 17:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_dataproject_submission_form_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproject',
            name='submission_form_html',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.models.get_submission_form_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html'])]),
        ),
    ]
