# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20180419_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantsubmission',
            name='submission_form_answers',
            field=models.CharField(blank=True, default=None, max_length=2500, null=True),
        ),
    ]
