# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_participantsubmission_submission_form_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantsubmission',
            name='submission_form_answers',
        ),
        migrations.AddField(
            model_name='participantsubmission',
            name='submission_info',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
