# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0036_auto_20180420_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSubmissionsDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_date', models.DateTimeField(auto_now_add=True)),
                ('participant_submissions', models.ManyToManyField(to='projects.ParticipantSubmission')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='participantsubmissiondownload',
            name='participant_submission',
        ),
        migrations.RemoveField(
            model_name='participantsubmissiondownload',
            name='user',
        ),
        migrations.DeleteModel(
            name='ParticipantSubmissionDownload',
        ),
    ]
