# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20180424_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantsubmission',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
