# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_participantsubmission_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreementform',
            name='form_html',
        ),
        migrations.RemoveField(
            model_name='dataproject',
            name='submission_form_html',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='logo',
        ),
        migrations.AddField(
            model_name='agreementform',
            name='form_file_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dataproject',
            name='submission_form_file_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='logo_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
