# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_auto_20180501_1501'),
        ('projects', '0038_dataproject_show_jwt'),
    ]

    operations = [
    ]
