# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_merge_20180503_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='has_teams',
            field=models.BooleanField(default=False),
        ),
    ]
