# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_dataproject_has_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayerDBForm',
            fields=[
                ('signedagreementform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.SignedAgreementForm')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Your name')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Your title')),
                ('harvard_address', models.CharField(max_length=255, null=True, verbose_name='Harvard Address')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Phone Number')),
                ('primary_department', models.CharField(max_length=255, null=True, verbose_name='Primary Harvard Department')),
                ('specific_aims', models.TextField(null=True, verbose_name="Please provide a concise 'specific aims page style description of the proposed work")),
                ('number_team_access', models.CharField(max_length=255, null=True, verbose_name='Approximately how many team members will require access to the HDS database?')),
                ('team_sql', models.CharField(max_length=255, null=True, verbose_name='Are the team members familiar with relational databases and the SQL programming language?')),
                ('team_r', models.CharField(max_length=255, null=True, verbose_name='Are the team members familiar with the R programming environment?')),
                ('team_orchestra', models.CharField(max_length=255, null=True, verbose_name='Are the team members familiar with HMS’ Orchestra cluster computing environment?')),
                ('team_windows', models.CharField(max_length=255, null=True, verbose_name='Are the team members familiar with the Windows Server environment and if so, do they have experience working remotely on a Windows platform using Remote Desktop?')),
                ('team_analysis', models.CharField(max_length=255, null=True, verbose_name='What is your team’s preferred analysis platform (list all that apply, e.g., R, Matlab, Python, SAS)?')),
                ('team_interests', models.CharField(max_length=255, null=True, verbose_name='Please briefly list the primary research interests of your team (e.g., “healthcare economics”, “viral epidemiology”, etc.)')),
                ('funding', models.CharField(max_length=255, null=True, verbose_name='Please list any relevant funding sources for this work')),
                ('protocol_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Do you have an existing IRB protocol that covers the proposed work? If so, please provide the protocol number and a copy of the approved proposal.')),
                ('signature', models.CharField(max_length=255, null=True, verbose_name='By signing this form, I acknowledge that I have read and agreed to the following terms of use, and will abide by them during the study period.')),
            ],
            bases=('projects.signedagreementform',),
        ),
        migrations.CreateModel(
            name='PayerDBProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('funding_status', models.CharField(max_length=250)),
                ('specific_aims', models.CharField(max_length=255, null=True, verbose_name='Specific Aims')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='dataproject',
            name='agreement_forms_required',
        ),
        migrations.AddField(
            model_name='agreementform',
            name='type',
            field=models.CharField(blank=True, choices=[('STATIC', 'STATIC'), ('DJANGO', 'DJANGO')], max_length=50, null=True),
        ),
    ]
