# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_auto_20180515_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayerDBParticipant',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.Participant')),
                ('dua_signed', models.BooleanField(default=False)),
                ('dua_sign_date', models.DateField()),
                ('access_status', models.CharField(max_length=255, null=True, verbose_name='Access Status')),
                ('ecommons_id', models.CharField(max_length=255, null=True, verbose_name='eCommons')),
                ('ip_address', models.CharField(max_length=255, null=True, verbose_name='IP Address')),
            ],
            bases=('projects.participant',),
        ),
        migrations.RemoveField(
            model_name='payerdbproject',
            name='specific_aims',
        ),
    ]
