# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_auto_20180621_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementform',
            name='external_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='agreementform',
            name='type',
            field=models.CharField(blank=True, choices=[('STATIC', 'STATIC'), ('DJANGO', 'DJANGO'), ('EXTERNAL_LINK', 'EXTERNAL LINK')], max_length=50, null=True),
        ),
    ]
