# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_auto_20180621_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementform',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
