# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_agreementform_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataproject',
            name='project_supervisor',
        ),
        migrations.AddField(
            model_name='dataproject',
            name='project_supervisors',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Project Supervisors (comma-delimited, no spaces)'),
        ),
    ]
