# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 19:28
from __future__ import unicode_literals

from django.db import migrations, models

def create_n2c2t1_submission_type(apps, schema_editor):

    DataProject = apps.get_model("projects", "dataproject")
    DataProjectSubmissionType = apps.get_model("projects", "dataprojectsubmissiontype")

    try:
        n2c2t1_project = DataProject.objects.get(project_key="n2c2-t1")

        DataProjectSubmissionType.objects.create(
            data_project=n2c2t1_project,
            title='Task',
            description='',
            submission_form_file_path='n2c2-t1.html',
            max_submissions=3,
            opened_time=None,
            closed_time=None,
            enabled=True,
        )
    except Exception:
        pass


def convert_dataprojectsubmissions(apps, schema_editor):
    """
    At this time, all DataProjectSubmission records belong to the n2c2-t1 data project.
    """

    DataProject = apps.get_model("projects", "dataproject")
    DataProjectSubmissionType = apps.get_model("projects", "dataprojectsubmissiontype")
    DataProjectSubmission = apps.get_model("projects", "dataprojectsubmission")

    try:
        n2c2t1_project = DataProject.objects.get(project_key="n2c2-t1")
        n2c2t1_submissiontype = DataProjectSubmissionType.objects.get(data_project=n2c2t1_project)

        # Set the submission type for every submission
        for submission in DataProjectSubmission.objects.all():
            submission.dataprojectsubmissiontype = n2c2t1_submissiontype
            submission.save()
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_auto_20180813_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprojectsubmissiontype',
            name='submission_form_file_path',
            field=models.CharField(max_length=300, blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='dataproject',
            name='submission_form_file_path',
        ),
        migrations.RunPython(create_n2c2t1_submission_type),
        migrations.AddField(
            model_name='dataprojectsubmission',
            name='submission_form_file_path',
            field=models.CharField(max_length=300, blank=True, null=True),
        ),
        migrations.RunPython(convert_dataprojectsubmissions),
    ]
