# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_auto_20180813_2004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataProjectSubmissionType',
            new_name='ChallengeTask',
        ),
        migrations.RenameField(
            model_name='dataprojectsubmission',
            old_name='dataprojectsubmissiontype',
            new_name='challenge_task',
        ),
    ]
