# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_auto_20180814_1515'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataProjectSubmission',
            new_name='ChallengeTaskSubmission',
        ),
    ]
