# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_auto_20180814_1515'),
    ]

    operations = [
        # For some reason, this migration error will occur:
        #   "Unknown column 'dataprojectsubmission_id' in 'projects_teamsubmissionsdownload_participant_submissions'"
        # To resolve this, rename the column before renaming the model. Requires sqlparse library installed.
        migrations.RunSQL(
            "ALTER TABLE projects_teamsubmissionsdownload_participant_submissions CHANGE COLUMN participantsubmission_id dataprojectsubmission_id char(32);"
        ),
        migrations.RenameModel(
            old_name='DataProjectSubmission',
            new_name='ChallengeTaskSubmission',
        ),
    ]
