# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_remove_dataproject_accepting_user_submissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostedFileSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.DataProject')),
            ],
        ),
        migrations.AddField(
            model_name='hostedfile',
            name='hostedfileset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.HostedFileSet'),
        ),
    ]
