# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_auto_20180817_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedfile',
            name='closed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostedfile',
            name='opened_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
