# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 14:28
from __future__ import unicode_literals
import uuid

from django.db import migrations, models

def create_uuid(apps, schema_editor):
    HostedFile = apps.get_model('projects', 'HostedFile')
    for hf in HostedFile.objects.all():
        hf.uuid = uuid.uuid4()
        hf.save()

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_auto_20180917_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedfile',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='hostedfile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False, null=False)
        )
    ]
