# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_hostedfile_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datagate',
            name='project',
        ),
        migrations.RemoveField(
            model_name='hostedfile',
            name='file_location_type',
        ),
        migrations.DeleteModel(
            name='DataGate',
        ),
    ]
