# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_auto_20181003_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payerdbform',
            name='signedagreementform_ptr',
        ),
        migrations.RemoveField(
            model_name='payerdbparticipant',
            name='participant_ptr',
        ),
        migrations.DeleteModel(
            name='PayerDBProject',
        ),
        migrations.AlterField(
            model_name='agreementform',
            name='type',
            field=models.CharField(blank=True, choices=[('STATIC', 'STATIC'), ('EXTERNAL_LINK', 'EXTERNAL LINK')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='PayerDBForm',
        ),
        migrations.DeleteModel(
            name='PayerDBParticipant',
        ),
    ]
