# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-09 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0062_auto_20181106_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataproject',
            name='permission_scheme',
        ),
        migrations.AddField(
            model_name='dataproject',
            name='require_authorization',
            field=models.BooleanField(default=True),
        ),
    ]
