# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-27 15:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0064_auto_20181109_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeTaskSubmissionDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_date', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ChallengeTaskSubmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='teamsubmissionsdownload',
            name='participant_submissions',
        ),
        migrations.RemoveField(
            model_name='teamsubmissionsdownload',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamsubmissionsdownload',
            name='user',
        ),
        migrations.DeleteModel(
            name='TeamSubmissionsDownload',
        ),
    ]
