# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-28 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_auto_20181127_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengetask',
            name='max_submissions',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
