# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0067_auto_20181129_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengetask',
            name='notify_admins_of_submissions',
        ),
        migrations.AddField(
            model_name='challengetask',
            name='notify_supervisors_of_submissions',
            field=models.BooleanField(default=False, help_text="Sends a notification to any emails listed in the project's supervisors field."),
        ),
    ]
