# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-10 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0068_auto_20181129_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='data_challenge',
            new_name='project',
        ),
    ]
