# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-28 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0069_auto_20190110_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengetasksubmission',
            name='challenge_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.ChallengeTask'),
        ),
        migrations.AlterField(
            model_name='challengetasksubmission',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Participant'),
        ),
        migrations.AlterField(
            model_name='challengetasksubmissiondownload',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.ChallengeTaskSubmission'),
        ),
        migrations.AlterField(
            model_name='challengetasksubmissiondownload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hostedfile',
            name='hostedfileset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.HostedFileSet'),
        ),
        migrations.AlterField(
            model_name='hostedfiledownload',
            name='hosted_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.HostedFile'),
        ),
        migrations.AlterField(
            model_name='hostedfiledownload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signedagreementform',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.DataProject'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teamcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
