# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-02 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0070_auto_20190328_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedfile',
            name='order',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
