# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-02 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_hostedfile_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedfile',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
