# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-15 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0072_auto_20190402_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='order',
            field=models.IntegerField(blank=True, help_text='Indicate an order (lowest number = highest order) for how the DataProjects should be listed.', null=True),
        ),
        migrations.AlterField(
            model_name='hostedfile',
            name='order',
            field=models.IntegerField(blank=True, help_text='Indicate an order (lowest number = highest order) for files to appear within a DataProject.', null=True),
        ),
    ]
