# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0073_auto_20190415_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='informational_only',
            field=models.BooleanField(default=False, help_text='Set this to true if this project has no registration or participation steps and should only render the description panel. The Registration Open value will be ignored. The Requires Authorization flag should be set to false.'),
        ),
        migrations.AlterField(
            model_name='dataproject',
            name='registration_open',
            field=models.BooleanField(default=False, help_text='Set this to true if you want to allow users without existing permissions on this item to be able to sign up for access.'),
        ),
        migrations.AlterField(
            model_name='dataproject',
            name='requires_authorization',
            field=models.BooleanField(default=True, help_text="Set this to true if you want to explicitly require a user to have VIEW permissions on this project before they can access the project's downloads, uploads, etc."),
        ),
    ]
