# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0074_auto_20190501_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedfileset',
            name='order',
            field=models.IntegerField(blank=True, help_text='Indicate an order (lowest number = highest order) for file sets to appear within a DataProject.', null=True),
        ),
    ]
