# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0075_hostedfileset_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='is_dataset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataproject',
            name='is_software',
            field=models.BooleanField(default=False),
        ),
    ]
