# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-23 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0077_auto_20190621_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='permission',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
