# Generated by Django 2.2.15 on 2020-12-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0078_participant_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='closed_description',
            field=models.TextField(blank=True, null=True, verbose_name='Closed Description'),
        ),
    ]
