# Generated by Django 2.2.24 on 2021-11-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0080_auto_20211130_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementform',
            name='order',
            field=models.IntegerField(default=50),
        ),
    ]
