# Generated by Django 2.2.24 on 2021-12-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0081_agreementform_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementform',
            name='content',
            field=models.TextField(blank=True, help_text="If Agreement Form type is set to 'MODEL', the HTML set here will be rendered for the user", null=True),
        ),
        migrations.AlterField(
            model_name='agreementform',
            name='order',
            field=models.IntegerField(default=50, help_text='Indicate an order (lowest number = first listing) for how the Agreement Forms should be listed during registration workflows.'),
        ),
        migrations.AlterField(
            model_name='agreementform',
            name='type',
            field=models.CharField(blank=True, choices=[('STATIC', 'STATIC'), ('EXTERNAL_LINK', 'EXTERNAL LINK'), ('MODEL', 'MODEL')], max_length=50, null=True),
        ),
    ]
