# Generated by Django 2.2.25 on 2021-12-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0082_auto_20211201_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='signedagreementform',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='agreementform',
            name='type',
            field=models.CharField(blank=True, choices=[('STATIC', 'STATIC'), ('EXTERNAL_LINK', 'EXTERNAL LINK'), ('MODEL', 'MODEL'), ('FILE', 'FILE')], max_length=50, null=True),
        ),
    ]
