# Generated by Django 2.2.25 on 2021-12-10 17:24

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0083_signedagreementform_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementform',
            name='type',
            field=models.CharField(blank=True, choices=[('STATIC', 'STATIC'), ('EXTERNAL_LINK', 'EXTERNAL LINK'), ('MODEL', 'MODEL'), ('FILE', 'FILE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='signedagreementform',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[projects.models.validate_pdf_file]),
        ),
        migrations.CreateModel(
            name='MIMIC3SignedAgreementFormFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('signed_agreement_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.SignedAgreementForm')),
            ],
            options={
                'verbose_name': 'MIMIC3 Signed Agreement Form Fields',
                'verbose_name_plural': 'MIMIC3 Signed Agreement Forms Fields',
            },
        ),
    ]
