# Generated by Django 2.2.25 on 2021-12-10 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0084_auto_20211210_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signedagreementform',
            options={'verbose_name': 'Signed Agreement Form', 'verbose_name_plural': 'Signed Agreement Forms'},
        ),
        migrations.AddField(
            model_name='signedagreementform',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signedagreementform',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
