# Generated by Django 2.2.27 on 2022-03-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0088_signedagreementform_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='teams_source_message',
            field=models.TextField(blank=True, default='Teams approved there will be automatically added to this project but will need still need approval for this project.', null=True, verbose_name='Teams Source Message'),
        ),
    ]
