# Generated by Django 2.2.27 on 2022-04-26 21:39

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0089_dataproject_teams_source_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signedagreementform',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.signed_agreement_form_path, validators=[projects.models.validate_pdf_file]),
        ),
    ]
