# Generated by Django 2.2.28 on 2022-05-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0090_auto_20220426_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signedagreementform',
            name='agreement_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
