# Generated by Django 2.2.28 on 2022-08-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0092_auto_20220517_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengetask',
            name='submission_file_type',
            field=models.CharField(choices=[('zip', 'ZIP'), ('pdf', 'PDF')], default='zip', max_length=15),
        ),
        migrations.AddField(
            model_name='challengetasksubmission',
            name='file_type',
            field=models.CharField(choices=[('zip', 'ZIP'), ('pdf', 'PDF')], default='zip', max_length=15),
        ),
    ]
