# Generated by Django 2.2.28 on 2022-08-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0093_auto_20220810_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementform',
            name='internal',
            field=models.BooleanField(default=False, help_text='Internal agreement forms are never presented to participants and are only submitted by administrators on behalf of participants'),
        ),
    ]
