# Generated by Django 4.1.6 on 2023-02-14 17:07

from django.db import migrations, models

from projects.models import AgreementForm, SignedAgreementForm, Participant


def migrate_agreement_form_model(apps, schema_editor):
    """
    Sets the initial value of the created field to the existing value of the
    modified field.
    """
    for agreement_form in AgreementForm.objects.all():

        # Set the dates
        agreement_form.modified = agreement_form.created
        agreement_form.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0095_alter_agreementform_id_alter_challengetask_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='created',
            field=models.DateTimeField(default="2023-01-01T00:00:00.000Z"),
        ),
        migrations.AddField(
            model_name='participant',
            name='modified',
            field=models.DateTimeField(default="2023-01-01T00:00:00.000Z"),
        ),
        migrations.AddField(
            model_name='agreementform',
            name='modified',
            field=models.DateTimeField(default="2023-01-01T00:00:00.000Z"),
        ),
        migrations.AddField(
            model_name='challengetask',
            name='created',
            field=models.DateTimeField(default="2023-01-01T00:00:00.000Z"),
        ),
        migrations.AddField(
            model_name='challengetask',
            name='modified',
            field=models.DateTimeField(default="2023-01-01T00:00:00.000Z"),
        ),
        migrations.AddField(
            model_name='dataproject',
            name='created',
            field=models.DateTimeField(default="2023-01-01T00:00:00.000Z"),
        ),
        migrations.AddField(
            model_name='dataproject',
            name='modified',
            field=models.DateTimeField(default="2023-01-01T00:00:00.000Z"),
        ),
        migrations.AddField(
            model_name='hostedfile',
            name='created',
            field=models.DateTimeField(default="2023-01-01T00:00:00.000Z"),
        ),
        migrations.AddField(
            model_name='hostedfile',
            name='modified',
            field=models.DateTimeField(default="2023-01-01T00:00:00.000Z"),
        ),
        migrations.AddField(
            model_name='hostedfileset',
            name='created',
            field=models.DateTimeField(default="2023-01-01T00:00:00.000Z"),
        ),
        migrations.AddField(
            model_name='hostedfileset',
            name='modified',
            field=models.DateTimeField(default="2023-01-01T00:00:00.000Z"),
        ),
        migrations.AddField(
            model_name='institution',
            name='created',
            field=models.DateTimeField(default="2023-01-01T00:00:00.000Z"),
        ),
        migrations.AddField(
            model_name='institution',
            name='modified',
            field=models.DateTimeField(default="2023-01-01T00:00:00.000Z"),
        ),
        migrations.AddField(
            model_name='team',
            name='created',
            field=models.DateTimeField(default="2023-01-01T00:00:00.000Z"),
        ),
        migrations.AddField(
            model_name='team',
            name='modified',
            field=models.DateTimeField(default="2023-01-01T00:00:00.000Z"),
        ),
        migrations.AddField(
            model_name='teamcomment',
            name='created',
            field=models.DateTimeField(default="2023-01-01T00:00:00.000Z"),
        ),
        migrations.AddField(
            model_name='teamcomment',
            name='modified',
            field=models.DateTimeField(default="2023-01-01T00:00:00.000Z"),
        ),
        migrations.RunPython(migrate_agreement_form_model),
        migrations.AlterField(
            model_name='agreementform',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='challengetask',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='challengetask',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dataproject',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dataproject',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hostedfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hostedfile',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hostedfileset',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hostedfileset',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teamcomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teamcomment',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
