# Generated by Django 4.1.7 on 2023-04-04 18:33

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0098_group_dataproject_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
                ('provider', models.CharField(choices=[('s3', 'AWS S3')], default='s3', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='dataproject',
            name='bucket',
            field=models.ForeignKey(default=projects.models.Bucket.get_default_pk, help_text="Set this to a specific bucket where this project's files should be stored.", on_delete=django.db.models.deletion.SET_DEFAULT, to='projects.bucket'),
        ),
        migrations.AddField(
            model_name='hostedfile',
            name='bucket',
            field=models.ForeignKey(default=projects.models.Bucket.get_default_pk, help_text='Set this to a specific bucket where this file is stored.', on_delete=django.db.models.deletion.SET_DEFAULT, to='projects.bucket'),
        ),
        migrations.AddField(
            model_name='hostedfileset',
            name='bucket',
            field=models.ForeignKey(default=projects.models.Bucket.get_default_pk, help_text="Set this to a specific bucket where this set's files are stored.", on_delete=django.db.models.deletion.SET_DEFAULT, to='projects.bucket'),
        ),
    ]
