# Generated by Django 4.1.6 on 2023-02-14 17:07

from django.db import migrations, models

from projects.models import Participant, SignedAgreementForm


def migrate_participants_model(apps, schema_editor):
    """
    Attempts to set a roughly accurate date of when each object would have
    been created. This is calculated by fetching the date of the last
    signed SignedAgreementForm relevant to the DataProjects.
    """
    for participant in Participant.objects.all():

        # Fetch signed agreement forms
        signed_agreement_form = SignedAgreementForm.objects.filter(user=participant.user, project=participant.project).last()
        if signed_agreement_form:

            # Set the dates
            participant.created = signed_agreement_form.date_signed
            participant.modified = signed_agreement_form.date_signed

            # Do the update
            Participant.objects.filter(pk=participant.pk).update(
                created=signed_agreement_form.date_signed,
                modified=signed_agreement_form.date_signed
            )

        else:

            # Do the update
            Participant.objects.filter(pk=participant.pk).update(
                created="2018-02-20T00:00:00Z",
                modified="2018-02-20T00:00:00Z",
            )


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0099_bucket_dataproject_bucket_hostedfile_bucket_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_participants_model),
    ]
