# Generated by Django 4.2 on 2023-05-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0100_participant_created_participant_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengetask',
            name='submission_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
