# Generated by Django 4.2.4 on 2023-09-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0101_challengetask_submission_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementform',
            name='skippable',
            field=models.BooleanField(default=False, help_text='Allow participants to skip this step in instances where they have submitted the agreement form via email or some other means. They will be required to include the name and contact information of the person who they submitted their signed agreement form to.'),
        ),
    ]
