# Generated by Django 4.2.1 on 2023-06-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0102_agreementform_skippable'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='commercial_only',
            field=models.BooleanField(default=False, help_text='Commercial only projects are for commercial entities only'),
        ),
    ]
