# Generated by Django 4.2.14 on 2024-08-08 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0104_group_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementform',
            name='template',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='signedagreementform',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.signed_agreement_form_document_path),
        ),
        migrations.CreateModel(
            name='InstitutionalOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('signed_agreement_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.signedagreementform')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.dataproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionalMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.institutionalofficial')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
