# Generated by Django 4.2.14 on 2024-08-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0105_agreementform_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementform',
            name='institutional_signers',
            field=models.BooleanField(default=False, help_text='Allows institutional signers to sign for their members. This will auto-approve this agreement form for members whose institutional official has had their agreement form approved.'),
        ),
        migrations.AddField(
            model_name='dataproject',
            name='institutional_signers',
            field=models.BooleanField(default=False, help_text='Allows institutional signers to sign for their members. This will auto-approve agreement forms for members whose institutional official has had their agreement forms approved.'),
        ),
        migrations.AddField(
            model_name='institutionalofficial',
            name='member_emails',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InstitutionalMember',
        ),
    ]
