# Generated by Django 4.2.15 on 2024-08-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0106_agreementform_institutional_signers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementform',
            name='form_class',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
