# Generated by Django 4.2.16 on 2024-09-27 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0107_agreementform_form_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='data_use_report_agreement_form',
            field=models.ForeignKey(blank=True, help_text='The agreement form that will be filled out by a user with access during periodic access and data use reporting', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.agreementform'),
        ),
        migrations.AddField(
            model_name='dataproject',
            name='data_use_report_grace_period',
            field=models.IntegerField(blank=True, help_text='The number of days in which a user is allotted to complete their access and data use reporting before their access is revoked', null=True),
        ),
        migrations.AddField(
            model_name='dataproject',
            name='data_use_report_period',
            field=models.IntegerField(blank=True, help_text='The number of days after access being granted in which emails will be sent prompting users to report on the status of their access and use of data', null=True),
        ),
    ]
