# Generated by Django 4.2.16 on 2024-10-09 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0108_dataproject_access_reporting_agreement_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUseReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.dataproject')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.participant')),
                ('signed_agreement_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.signedagreementform')),
            ],
            options={
                'verbose_name': 'Data Use Report Request',
                'verbose_name_plural': 'Data Use Report Requests',
            },
        ),
    ]
