# Generated by Django 4.2.16 on 2024-10-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0109_datausereportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementform',
            name='handler',
            field=models.CharField(blank=True, help_text="Set an absolute function's path to be called after the SignedAgreementForm has successfully saved", max_length=512, null=True),
        ),
    ]
