# Generated by Django 4.2.21 on 2025-05-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0110_agreementform_handler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementform',
            name='type',
            field=models.CharField(blank=True, choices=[('STATIC', 'STATIC'), ('EXTERNAL_LINK', 'EXTERNAL LINK'), ('MODEL', 'MODEL'), ('FILE', 'FILE'), ('BLANK', 'BLANK')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dataproject',
            name='automatic_authorization',
            field=models.BooleanField(default=False, help_text='Set this to true if you want users to automatically be granted VIEW permissions on this project when they complete signup steps and request access. This is only applicable if the project is set to require authorization.'),
        ),
    ]
