# Generated by Django 4.2.21 on 2025-06-02 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
        ('projects', '0111_alter_agreementform_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProjectWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires_approval', models.BooleanField(default=False, help_text='Set this to true if this workflow requires approval before it can be marked as completed. This is used to determine if the workflow should be shown to users who have not yet been authorized for the project.')),
                ('post_authorization', models.BooleanField(default=False, help_text='Set this to true if this workflow is intended for post-authorization dashboards. This will be used to determine if the workflow should be shown to users who have not yet been authorized for the project.')),
                ('is_repeatable', models.BooleanField(default=False, help_text='Set this to true if this workflow can be repeated by users. This is used to determine if the workflow should be shown to users who have already completed it.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='projects.dataproject')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_project_workflows', to='workflows.workflow')),
            ],
            options={
                'unique_together': {('data_project', 'workflow')},
            },
        ),
    ]
