# Generated by Django 4.2.23 on 2025-08-01 17:26

from django.db import migrations
import hypatio.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0112_dataprojectworkflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mayosignedagreementformfields',
            name='signed_agreement_form',
        ),
        migrations.RemoveField(
            model_name='mimic3signedagreementformfields',
            name='signed_agreement_form',
        ),
        migrations.RemoveField(
            model_name='nlpduasignedagreementformfields',
            name='signed_agreement_form',
        ),
        migrations.RemoveField(
            model_name='nlpwhysignedagreementformfields',
            name='signed_agreement_form',
        ),
        migrations.RemoveField(
            model_name='rocsignedagreementformfields',
            name='signed_agreement_form',
        ),
        migrations.AlterField(
            model_name='challengetask',
            name='submission_instructions',
            field=hypatio.models.SanitizedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challengetasksubmission',
            name='submission_info',
            field=hypatio.models.SanitizedTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dataproject',
            name='description',
            field=hypatio.models.SanitizedTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dataproject',
            name='teams_source_message',
            field=hypatio.models.SanitizedTextField(blank=True, default='Teams approved there will be automatically added to this project but will need still need approval for this project.', null=True, verbose_name='Teams Source Message'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=hypatio.models.SanitizedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='institutionalofficial',
            name='institution',
            field=hypatio.models.SanitizedTextField(),
        ),
        migrations.AlterField(
            model_name='signedagreementform',
            name='agreement_text',
            field=hypatio.models.SanitizedTextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DUASignedAgreementFormFields',
        ),
        migrations.DeleteModel(
            name='MAYOSignedAgreementFormFields',
        ),
        migrations.DeleteModel(
            name='MIMIC3SignedAgreementFormFields',
        ),
        migrations.DeleteModel(
            name='NLPDUASignedAgreementFormFields',
        ),
        migrations.DeleteModel(
            name='NLPWHYSignedAgreementFormFields',
        ),
        migrations.DeleteModel(
            name='ROCSignedAgreementFormFields',
        ),
    ]
