# Generated by Django 4.2.23 on 2025-09-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0113_remove_mayosignedagreementformfields_signed_agreement_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementform',
            name='automatic_approval',
            field=models.BooleanField(default=False, help_text='Determines if signed agreement forms will be automatically approved by the system.'),
        ),
    ]
