repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: check-byte-order-marker
    - id: check-merge-conflict
    - id: detect-aws-credentials
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.4.0
    hooks:
      - id: pip-compile
        name: pip-compile dev-requirements.in
        args: [dev-requirements.in, --upgrade, --generate-hashes, --allow-unsafe, --output-file, dev-requirements.txt]
        files: ^dev-requirements\.(in|txt)$
      - id: pip-compile
        name: pip-compile requirements.in
        args: [requirements.in, --upgrade, --generate-hashes, --allow-unsafe, --output-file, requirements.txt]
        files: ^requirements\.(in|txt)$
