version: '2.1'
services:
  hypatio:
    environment:
      - AWS_SECRET_ACCESS_KEY=xaFUWTwFzZ2kCyVNwWVfaZYR040XBL+qELBjEn9s
      - AWS_ACCESS_KEY_ID=AKIAJSH4CELEGJ7GPJGA
      - PS_PATH=secret.dbmi.hypatio.DEV
    build:
      context: ~/Documents/virtualenvironments/hypatio-app
      dockerfile: Dockerfile
    volumes:
      - ~/Documents/virtualenvironments/hypatio-app/app:/app
  scireg:
    environment:
      - AWS_SECRET_ACCESS_KEY=xaFUWTwFzZ2kCyVNwWVfaZYR040XBL+qELBjEn9s
      - AWS_ACCESS_KEY_ID=AKIAJSH4CELEGJ7GPJGA
      - PS_PATH=secret.dbmi.scireg.DEV
    build:
      context: ~/Documents/virtualenvironments/scireg/SciReg
      dockerfile: Dockerfile
    volumes:
      - ~/Documents/virtualenvironments/scireg/SciReg/app:/app
  sciauth:
    environment:
      - AWS_SECRET_ACCESS_KEY=xaFUWTwFzZ2kCyVNwWVfaZYR040XBL+qELBjEn9s
      - AWS_ACCESS_KEY_ID=AKIAJSH4CELEGJ7GPJGA
      - PS_PATH=secret.dbmi.sciauth.DEV
    build:
      context: ~/Documents/virtualenvironments/sciauth/SciAuth
      dockerfile: Dockerfile
    volumes:
      - ~/Documents/virtualenvironments/sciauth/SciAuth/app:/app
  sciauthz:
    environment:
      - AWS_SECRET_ACCESS_KEY=xaFUWTwFzZ2kCyVNwWVfaZYR040XBL+qELBjEn9s
      - AWS_ACCESS_KEY_ID=AKIAJSH4CELEGJ7GPJGA
      - PS_PATH=secret.dbmi.sciauthz.DEV
    build:
      context: ~/Documents/virtualenvironments/SciAuthZ
      dockerfile: Dockerfile
    volumes:
      - ~/Documents/virtualenvironments/SciAuthZ/app:/app
networks:
  portal:
    driver: bridge
