version: '2.1'
services:
  hypatio:
    environment:
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - PS_PATH=secret.dbmi.hypatio.DEV
    build:
      context: ~/work/hypatio-app
      dockerfile: Dockerfile
    volumes:
      - ~/work/hypatio-app/app:/app
  scireg:
    environment:
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - PS_PATH=secret.dbmi.scireg.DEV
    build:
      context: ~/work/SciReg
      dockerfile: Dockerfile
    volumes:
      - ~/work/SciReg/app:/app
  sciauth:
    environment:
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - PS_PATH=secret.dbmi.sciauth.DEV
    build:
      context: ~/work/SciAuth
      dockerfile: Dockerfile
    volumes:
      - ~/work/SciAuth/app:/app
  sciauthz:
    environment:
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - PS_PATH=secret.dbmi.sciauthz.DEV
    build:
      context: ~/work/SciAuthZ
      dockerfile: Dockerfile
    volumes:
      - ~/work/SciAuthZ/app:/app
networks:
  portal:
    driver: bridge
