# Generated by Django 4.2.22 on 2025-06-11 16:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='indefinite',
            field=models.BooleanField(default=False, help_text="If true, this step will stay 'current' when set as such."),
        ),
        migrations.CreateModel(
            name='WorkflowDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='workflows.workflow')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='workflows.workflow')),
            ],
            options={
                'unique_together': {('workflow', 'depends_on')},
            },
        ),
    ]
