# Generated by Django 4.2.23 on 2025-07-06 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0003_rename_class_name_step_controller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepstate',
            name='data',
            field=models.JSONField(blank=True, db_column='data', help_text='The data from this Step', null=True),
        ),
        migrations.RenameField(
            model_name='stepstate',
            old_name='data',
            new_name='_data',
        ),
        migrations.AlterField(
            model_name='stepstate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uninitialized', 'Uninitialized'), ('current', 'Current'), ('unreviewed', 'Unreviewed'), ('completed', 'Completed'), ('indefinite', 'Indefinite')], db_column='status', default='pending', help_text='The current status of the step.', max_length=128),
        ),
        migrations.RenameField(
            model_name='stepstate',
            old_name='status',
            new_name='_status',
        ),
        migrations.CreateModel(
            name='StepStateFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('fileservice', 'Fileservice'), ('s3', 'S3')], help_text='The provider that is storing the file and determines how it is accessed.', max_length=128)),
                ('filename', models.CharField(help_text='The name of the file', max_length=512)),
                ('size', models.BigIntegerField(help_text='The size of the file in bytes')),
                ('url', models.CharField(help_text='The URL of the file', max_length=512)),
                ('data', models.JSONField(blank=True, help_text='The data from the file upload.', null=True)),
                ('media_type', models.CharField(help_text='The media type of the uploaded file.', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(help_text='The user who uploaded the file for the step.', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_step_state_files', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user who owns the file.', on_delete=django.db.models.deletion.CASCADE, related_name='step_state_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stepstateversion',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_state_version', to='workflows.stepstatefile'),
        ),
        migrations.AddField(
            model_name='stepstate',
            name='_file',
            field=models.OneToOneField(db_column="file", blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_state', to='workflows.stepstatefile'),
        ),
        migrations.AddField(
            model_name='stepstateinitialization',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initialization', to='workflows.stepstatefile'),
        ),
        migrations.AddField(
            model_name='stepstateversion',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workflows.stepstatereview'),
        ),
    ]
