# Generated by Django 4.2.23 on 2025-07-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_alter_stepstate_data_rename_data_stepstate__data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='controller',
            field=models.CharField(default='workflows.controllers.steps.BaseStepController', help_text='The fully-qualified class name for the step. This is used to determine how the step should be rendered and processed.', max_length=512),
        ),
        migrations.AlterField(
            model_name='step',
            name='initialization_required',
            field=models.BooleanField(default=False, help_text='Marks this step as needing an administrator initialization before it can be started.'),
        ),
        migrations.AlterField(
            model_name='step',
            name='review_required',
            field=models.BooleanField(default=False, help_text='Marks this step as needing an administrator review before it can be completed.'),
        ),
        migrations.AlterField(
            model_name='stepstatereview',
            name='step_state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='workflows.stepstate'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='controller',
            field=models.CharField(default='workflows.controllers.workflows.BaseWorkflowController', help_text='The fully-qualified class name for the workflow. This is used to determine how the workflow should be rendered and processed.', max_length=512),
        ),
        migrations.RemoveField(
            model_name='stepstateversion',
            name='review',
        ),
        migrations.AddField(
            model_name='stepstatereview',
            name='version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='workflows.stepstateversion'),
        ),
    ]
