# Generated by Django 4.2.23 on 2025-08-01 17:26

from django.db import migrations
import hypatio.models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_alter_step_controller_and_more_squashed_0007_remove_stepstateversion_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='description',
            field=hypatio.models.SanitizedTextField(blank=True, help_text='A description of the step. This is used to provide context to users about what the step entails.', null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='initialization_message',
            field=hypatio.models.SanitizedTextField(default='Your current step on the DBMI Data Portal has been initialized and is ready for you to continue.', help_text='The message that users will receive when the current step has been initialized. The email will also include a link for the user to return to the step.'),
        ),
        migrations.AlterField(
            model_name='step',
            name='review_message',
            field=hypatio.models.SanitizedTextField(default='Your recently completed step on the DBMI Data Portal has been reviewed. Please return to the dashboard to check the status of the step.', help_text='The default message that users will receive when the current step has been reviewed. The email will also include a link for the user to return to the step.'),
        ),
        migrations.AlterField(
            model_name='stepstateinitialization',
            name='message',
            field=hypatio.models.SanitizedTextField(blank=True, help_text='An optional message describing the initialization of the step. This can be used to provide context or feedback on the actions made.', null=True),
        ),
        migrations.AlterField(
            model_name='stepstatereview',
            name='message',
            field=hypatio.models.SanitizedTextField(blank=True, help_text='An optional message describing the review of the step. This can be used to provide context or feedback on the decision made.', null=True),
        ),
        migrations.AlterField(
            model_name='stepstateversion',
            name='message',
            field=hypatio.models.SanitizedTextField(blank=True, help_text='An optional message describing the changes made in this version. This can be used to provide context or feedback on the changes made.', null=True),
        ),
        migrations.AlterField(
            model_name='videostep',
            name='thumbnail_url',
            field=hypatio.models.SanitizedTextField(blank=True, help_text='An optional thumbnail URL for the video. This can be used to show a preview of the video before it is played.', null=True),
        ),
        migrations.AlterField(
            model_name='videostep',
            name='video_url',
            field=hypatio.models.SanitizedTextField(help_text='The URL of the video to show in this step.'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=hypatio.models.SanitizedTextField(blank=True, help_text='A description of the workflow. This is used to provide context to users about what the workflow entails.', null=True),
        ),
    ]
