# Generated by Django 4.2.23 on 2025-09-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_alter_step_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatype',
            name='name',
            field=models.CharField(blank=True, help_text='The optional name of this media type to be used in the interface', max_length=255, null=True),
        ),
    ]
