# Generated by Django 4.2.23 on 2025-09-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_mediatype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTypeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this media type group', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('media_types', models.ManyToManyField(help_text='The media types that comprise this grouping', to='workflows.mediatype')),
            ],
        ),
    ]
