"""
Django settings for hypatio project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

DEBUG = True

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SECRET_KEY = "TEST"

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

AUTH0_DOMAIN = 'mtmcduffie.auth0.com'
AUTH0_CLIENT_ID = 'y16slzzzDr9jKhEHsZZmKYskQdJKoMFm'
AUTH0_SECRET = 'NERqMWdCeGhKUHhxMlh1ZVV3Z3AwVENOY0N0V0xqaG1peFgtcHJ0TkVLejhwLXZkVFJJN2V3M1U0Rjctd3lmdw=='
AUTH0_CALLBACK_URL = 'http://localhost:8000/login/callback_handling/'
AUTH0_SUCCESS_URL = '/login/landingpage/'
AUTH0_LOGOUT_URL = 'https://mtmcduffie.auth0.com/v2/logout?returnTo=http://localhost:8000'

ACCOUNT_SERVER_URL = 'http://localhost:8001/auth'

SCIREG_SERVER_URL = "http://localhost:8005"

AUTHZ_BASE = "http://localhost:8003"

PERMISSION_SERVER = AUTHZ_BASE + "/user_permission/"
PROJECT_PERMISSION_URL = AUTHZ_BASE + "/authorizable_projects/"
PROJECT_SETUP_URL = AUTHZ_BASE + "/project_setup/"
CREATE_REQUEST_URL = AUTHZ_BASE + "/authorization_requests/"
CREATE_DUA_SIGN = AUTHZ_BASE + "/dua_sign/"
GET_ACCESS_REQUESTS = AUTHZ_BASE + "/authorization_requests/"
LOGIN_URL = '/login/'
AUTHENTICATION_LOGIN_URL = 'http://localhost:8001/login/auth'

SESSION_COOKIE_AGE = 5 * 60

COOKIE_DOMAIN = "localhost"