# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-10 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name=b'Name of Challenge')),
                ('institution', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Institution')),
                ('description', models.CharField(blank=True, max_length=4000, null=True, verbose_name=b'Description')),
                ('short_description', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Short Description')),
                ('challenge_key', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name=b'Challenge Key')),
                ('permission_scheme', models.CharField(default=b'PRIVATE', max_length=100, verbose_name=b'Permission Scheme')),
                ('dua_required', models.BooleanField(default=True)),
                ('challenge_supervisor', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Challenge Supervisor')),
            ],
        ),
    ]
