# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprojects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='project_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Project Key'),
        ),
    ]
