# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprojects', '0003_dataproject_permission_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='project_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Project URL'),
        ),
    ]
