# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of project')),
                ('institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Institution')),
                ('description', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Description')),
                ('short_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Short Description')),
            ],
        ),
    ]
