# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-14 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprojects', '0005_remove_dataproject_permission_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='dua_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dataproject',
            name='permission_scheme',
            field=models.CharField(default=b'PRIVATE', max_length=100, verbose_name=b'Permission Scheme'),
        ),
        migrations.AddField(
            model_name='dataproject',
            name='project_supervisor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Project Supervisor'),
        ),
    ]
