# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-18 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprojects', '0006_auto_20171214_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUseAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'name')),
                ('agreement_form_file', models.CharField(blank=True, max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duas', to='dataprojects.DataProject')),
            ],
        ),
    ]
