# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-18 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataprojects', '0007_datauseagreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUseAgreementSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('agreement_text', models.TextField()),
                ('data_use_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprojects.DataUseAgreement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
