# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-18 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprojects', '0008_datauseagreementsign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproject',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name=b'Name of project'),
        ),
        migrations.AlterField(
            model_name='dataproject',
            name='project_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name=b'Project Key'),
        ),
    ]
