name: Scan

on:
  pull_request:
    branches: [ master, development ]
  schedule:
    - cron: '0 12 * * 1' # runs at 12:00 UTC on Mondays
  workflow_dispatch:

jobs:
  scan:
    uses: hms-dbmi/actions/.github/workflows/scan.yml@main
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.BLHMSDBMI_DOCKERHUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.BLHMSDBMI_DOCKERHUB_PASSWORD }}
    with:
      repository: ${{ github.repository }}
      commit: ${{ github.sha }}
