name: Test

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Set image name
      id: setimagename
      run: |
          echo "Image name: $GITHUB_REPOSITORY:$GITHUB_SHA"
          echo "::set-output name=imagename::$GITHUB_REPOSITORY:$GITHUB_SHA"

    - name: Build the image
      id: buildimage
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: false
        tags: ${{ steps.setimagename.outputs.imagename }}
